name: Autodeploy prod
on:
  push:
    branches: [master]
jobs:
  Deploy:
    runs-on: self-hosted
    environment: prod
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - run: npm ci
      - name: set config
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "config.json"
          json: ${{ secrets.CONFIG }}
          dir: './config'
      - run: npm run build
