name: Autodeploy dev
on: 
  push:
    branches: [ dev ]
jobs:
  Deploy:
    runs-on: self-hosted
    environment: 
      name: dev
      url: https://github.com
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - run: env
      #- run: cd /home/petfinder/envs/dev/frontend && cp local.json /home/petfinder/github-actions/frontend/_work/petfinder/petfinder/config
      #- run: npm ci
      #- run: cd config && echo "${{ github.env.dev.local }}" > local.json
      #- run: npm run build