name: Autodeploy dev
on:
  push:
    branches: [dev]
jobs:
  Deploy:
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - run: env
      - run: npm ci
      #- run: cd config && echo "${{ secrets.CONFIG }}" > local.json
      - run: cd config && echo "{\"API\": \"https://dev.petfinder.com.ua/api\",\"MAPS\": \"AIzaSyDFcgjFmW1IFDT8TV-fce4iFWvN3PA148g\",\"PORT\": 4000}" > local.json
      - run: npm run build
