name: Autodeploy dev
on: 
  push:
    branches: [ dev ]
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - run: npm ci
      - run: npm run build