name: Autodeploy dev
on: 
  push:
    branches: [ dev ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: ssh {{ secrets.ssh_user }}@{{ ssh.ip }} -p {{ ssh.port }}
      - run: mkdir test
