name: Autodeploy dev
on: 
  push:
    branches: [ master ]
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      #- run: cd ~/envs/petfinder-dev && cp local.json ~/deploy/deploy/petfinder/petfinder/config
      #- run: npm ci
      #- run: npm run build
      #- run: cp -R ~/deploy/deploy/petfinder/petfinder ~/dev