name: Autodeploy dev
on: 
  push:
    branches: [ dev ]
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - run: cd /home/petfinder/envs/petfinder-dev && cp local.json /home/petfinder/github-actions/frontend/_work/petfinder/petfinder/config
      - run: npm ci
      - run: npm run build
      - run: cp -R /home/petfinder/github-actions/frontend/_work/petfinder/petfinder /home/petfinder/dev